# Generated by Django 4.2.2 on 2023-06-19 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availability',
            old_name='end_time',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='availability',
            old_name='start_time',
            new_name='start',
        ),
    ]
