# Generated by Django 4.2.2 on 2023-06-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_alter_availability_options_remove_room_availability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='room',
        ),
        migrations.AddField(
            model_name='room',
            name='availability',
            field=models.ManyToManyField(to='rooms.availability'),
        ),
    ]
